"""initial schema

Revision ID: 63138ed9c3fe
Revises: 
Create Date: 2026-09-07 21:14:03.890092
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '63138ed9c3fe'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('niche', sa.String(length=200), nullable=False),
    sa.Column('audience', sa.String(length=300), nullable=False),
    sa.Column('language', sa.String(length=40), nullable=False),
    sa.Column('tone', sa.String(length=120), nullable=False),
    sa.Column('content_style', sa.String(length=120), nullable=False),
    sa.Column('video_length_min', sa.Integer(), nullable=False),
    sa.Column('posting_frequency', sa.String(length=40), nullable=False),
    sa.Column('timezone', sa.String(length=60), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channels'))
    )
    op.create_index(op.f('ix_channels_slug'), 'channels', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'editor', 'viewer', name='userrole', native_enum=False, length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('channel_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('approval_mode', sa.Enum('AUTO', 'APPROVAL_REQUIRED', 'MANUAL', name='approvalmode', native_enum=False, length=40), nullable=False),
    sa.Column('automation_enabled', sa.Boolean(), nullable=False),
    sa.Column('daily_video_limit', sa.Integer(), nullable=False),
    sa.Column('publish_time', sa.String(length=5), nullable=False),
    sa.Column('privacy_default', sa.Enum('private', 'unlisted', 'public', name='privacystatus', native_enum=False, length=40), nullable=False),
    sa.Column('allow_unverified_media', sa.Boolean(), nullable=False),
    sa.Column('notify_events', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('topic_ai', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('script_ai', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('research_cfg', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('voice_cfg', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('visual_cfg', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('thumbnail_cfg', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('youtube_cfg', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('whatsapp_cfg', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scoring_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_channel_settings_channel_id_channels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_settings')),
    sa.UniqueConstraint('channel_id', name=op.f('uq_channel_settings_channel_id'))
    )
    op.create_table('scheduler_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('lock_key', sa.String(length=120), nullable=False),
    sa.Column('jobs_created', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_scheduler_runs_channel_id_channels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduler_runs')),
    sa.UniqueConstraint('channel_id', 'run_date', name='uq_scheduler_runs_channel_id_run_date'),
    sa.UniqueConstraint('lock_key', name=op.f('uq_scheduler_runs_lock_key'))
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('hook', sa.Text(), nullable=False),
    sa.Column('angle', sa.Text(), nullable=False),
    sa.Column('audience', sa.String(length=300), nullable=False),
    sa.Column('estimated_interest', sa.Float(), nullable=False),
    sa.Column('uniqueness_score', sa.Float(), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('search_potential', sa.Float(), nullable=False),
    sa.Column('retention_potential', sa.Float(), nullable=False),
    sa.Column('competition', sa.Float(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('evergreen', sa.Boolean(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('GENERATED', 'APPROVED', 'REJECTED', 'USED', name='topicstatus', native_enum=False, length=40), nullable=False),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_topics_channel_id_channels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name='fk_topics_job_id_jobs', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics')),
    sa.UniqueConstraint('channel_id', 'fingerprint', name='uq_topics_channel_id_fingerprint')
    )
    op.create_index('ix_topics_channel_status', 'topics', ['channel_id', 'status'], unique=False)
    op.create_index(op.f('ix_topics_fingerprint'), 'topics', ['fingerprint'], unique=False)
    op.create_table('youtube_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('youtube_channel_id', sa.String(length=80), nullable=True),
    sa.Column('channel_title', sa.String(length=200), nullable=True),
    sa.Column('access_token_enc', sa.Text(), nullable=True),
    sa.Column('refresh_token_enc', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_youtube_credentials_channel_id_channels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_youtube_credentials')),
    sa.UniqueConstraint('channel_id', name=op.f('uq_youtube_credentials_channel_id'))
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=40), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('AUTO', 'APPROVAL_REQUIRED', 'MANUAL', name='approvalmode', native_enum=False, length=40), nullable=False),
    sa.Column('test_run', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'WAITING_APPROVAL', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus', native_enum=False, length=40), nullable=False),
    sa.Column('current_stage', sa.Enum('TOPIC', 'RESEARCH', 'SCRIPT', 'SCRIPT_QA', 'VOICE', 'VISUALS', 'SUBTITLES', 'TIMELINE', 'RENDER', 'THUMBNAIL', 'METADATA', 'FINAL_QA', 'APPROVAL_GATE', 'UPLOAD', 'NOTIFY', 'COMPLETE', name='stage', native_enum=False, length=40), nullable=False),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('preset_topic_id', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=40), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('total_duration_sec', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_jobs_channel_id_channels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_jobs_topic_id_topics'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index('ix_jobs_channel_status', 'jobs', ['channel_id', 'status'], unique=False)
    op.create_index(op.f('ix_jobs_public_id'), 'jobs', ['public_id'], unique=True)
    op.create_index('ix_jobs_status_created', 'jobs', ['status', 'created_at'], unique=False)
    op.create_table('api_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=40), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('operation', sa.String(length=60), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('seconds', sa.Float(), nullable=False),
    sa.Column('est_cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_api_usage_job_id_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_usage'))
    )
    op.create_index('ix_api_usage_created', 'api_usage', ['created_at'], unique=False)
    op.create_index('ix_api_usage_job', 'api_usage', ['job_id'], unique=False)
    op.create_table('job_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('TOPIC', 'RESEARCH', 'SCRIPT', 'SCRIPT_QA', 'VOICE', 'VISUALS', 'SUBTITLES', 'TIMELINE', 'RENDER', 'THUMBNAIL', 'METADATA', 'FINAL_QA', 'APPROVAL_GATE', 'UPLOAD', 'NOTIFY', 'COMPLETE', name='stage', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED', name='jobstepstatus', native_enum=False, length=40), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_code', sa.String(length=40), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retryable', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_steps_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_steps')),
    sa.UniqueConstraint('job_id', 'stage', 'attempt', name='uq_job_steps_job_id_stage_attempt')
    )
    op.create_index('ix_job_steps_job_stage', 'job_steps', ['job_id', 'stage'], unique=False)
    op.create_table('music_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('none', 'uploaded', 'licensed', 'generated', name='musicsource', native_enum=False, length=40), nullable=False),
    sa.Column('file_key', sa.String(length=400), nullable=True),
    sa.Column('license', sa.String(length=200), nullable=False),
    sa.Column('attribution', sa.String(length=400), nullable=False),
    sa.Column('duck_level_pct', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_music_tracks_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_music_tracks'))
    )
    op.create_index(op.f('ix_music_tracks_job_id'), 'music_tracks', ['job_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.Enum('job_started', 'video_ready', 'published', 'error', name='notificationevent', native_enum=False, length=40), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('recipient', sa.String(length=120), nullable=False),
    sa.Column('template', sa.String(length=60), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'sent', 'delivered', 'read', 'failed', name='notificationstatus', native_enum=False, length=40), nullable=False),
    sa.Column('provider_message_id', sa.String(length=120), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_notifications_channel_id_channels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_notifications_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('job_id', 'event', name='uq_notifications_job_id_event')
    )
    op.create_table('research',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('opinions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_research_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_research_topic_id_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research'))
    )
    op.create_table('scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'QA_FAILED', 'APPROVED', 'REJECTED', 'FINAL', name='scriptstatus', native_enum=False, length=40), nullable=False),
    sa.Column('target_duration_sec', sa.Integer(), nullable=False),
    sa.Column('tone', sa.String(length=120), nullable=False),
    sa.Column('style', sa.String(length=120), nullable=False),
    sa.Column('language', sa.String(length=40), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('qa_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_scripts_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_scripts_topic_id_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scripts'))
    )
    op.create_index(op.f('ix_scripts_job_id'), 'scripts', ['job_id'], unique=False)
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=True),
    sa.Column('event', sa.String(length=80), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_system_logs_job_id_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_logs'))
    )
    op.create_index('ix_system_logs_job_created', 'system_logs', ['job_id', 'created_at'], unique=False)
    op.create_index('ix_system_logs_level_created', 'system_logs', ['level', 'created_at'], unique=False)
    op.create_table('thumbnails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('concept', sa.Text(), nullable=False),
    sa.Column('text', sa.String(length=120), nullable=False),
    sa.Column('composition', sa.Text(), nullable=False),
    sa.Column('target_emotion', sa.String(length=60), nullable=False),
    sa.Column('image_prompt', sa.Text(), nullable=False),
    sa.Column('file_key', sa.String(length=400), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('est_cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_thumbnails_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_thumbnails'))
    )
    op.create_index(op.f('ix_thumbnails_job_id'), 'thumbnails', ['job_id'], unique=False)
    op.create_table('youtube_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=60)), nullable=False),
    sa.Column('hashtags', postgresql.ARRAY(sa.String(length=60)), nullable=False),
    sa.Column('category_id', sa.String(length=10), nullable=False),
    sa.Column('playlist_id', sa.String(length=80), nullable=True),
    sa.Column('chapters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('title_options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('privacy_status', sa.Enum('private', 'unlisted', 'public', name='privacystatus', native_enum=False, length=40), nullable=False),
    sa.Column('scheduled_publish_at', sa.DateTime(), nullable=True),
    sa.Column('youtube_video_id', sa.String(length=40), nullable=True),
    sa.Column('youtube_url', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('draft', 'uploading', 'uploaded', 'scheduled', 'published', 'failed', name='uploadstatus', native_enum=False, length=40), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('quota_units_used', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_youtube_uploads_channel_id_channels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_youtube_uploads_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_youtube_uploads')),
    sa.UniqueConstraint('job_id', name=op.f('uq_youtube_uploads_job_id'))
    )
    op.create_table('script_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('body_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('est_duration_sec', sa.Integer(), nullable=False),
    sa.Column('qa_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], name=op.f('fk_script_versions_script_id_scripts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_script_versions')),
    sa.UniqueConstraint('script_id', 'version', name='uq_script_versions_script_id_version')
    )
    op.create_table('video_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('aspect_ratio', sa.Enum('16:9', '9:16', '1:1', name='aspectratio', native_enum=False, length=40), nullable=False),
    sa.Column('resolution', sa.String(length=20), nullable=False),
    sa.Column('timeline_key', sa.String(length=400), nullable=True),
    sa.Column('video_key', sa.String(length=400), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('has_subtitles', sa.Boolean(), nullable=False),
    sa.Column('music_track_id', sa.Integer(), nullable=True),
    sa.Column('thumbnail_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('rendering', 'ready', 'failed', name='videostatus', native_enum=False, length=40), nullable=False),
    sa.Column('ffprobe', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_video_projects_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['music_track_id'], ['music_tracks.id'], name=op.f('fk_video_projects_music_track_id_music_tracks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thumbnail_id'], ['thumbnails.id'], name=op.f('fk_video_projects_thumbnail_id_thumbnails'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_video_projects')),
    sa.UniqueConstraint('job_id', name=op.f('uq_video_projects_job_id'))
    )
    op.create_table('video_scenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('scene_index', sa.Integer(), nullable=False),
    sa.Column('narration', sa.Text(), nullable=False),
    sa.Column('visual_prompt', sa.Text(), nullable=False),
    sa.Column('visual_type', sa.Enum('image', 'ai_video', 'stock', 'upload', name='visualtype', native_enum=False, length=40), nullable=False),
    sa.Column('planned_duration_sec', sa.Float(), nullable=False),
    sa.Column('actual_duration_sec', sa.Float(), nullable=True),
    sa.Column('transition', sa.String(length=40), nullable=False),
    sa.Column('caption_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_video_scenes_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], name=op.f('fk_video_scenes_script_id_scripts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_video_scenes'))
    )
    op.create_index('ix_video_scenes_job_scene', 'video_scenes', ['job_id', 'scene_index'], unique=False)
    op.create_table('visual_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('source', sa.Enum('ai_image', 'ai_video', 'stock', 'upload', name='assetsource', native_enum=False, length=40), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('file_key', sa.String(length=400), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('license', sa.String(length=200), nullable=False),
    sa.Column('attribution', sa.String(length=400), nullable=False),
    sa.Column('rights_verified', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('est_cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_visual_assets_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['video_scenes.id'], name=op.f('fk_visual_assets_scene_id_video_scenes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visual_assets'))
    )
    op.create_index(op.f('ix_visual_assets_job_id'), 'visual_assets', ['job_id'], unique=False)
    op.create_table('voiceovers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('script_version_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('voice', sa.String(length=120), nullable=False),
    sa.Column('language', sa.String(length=40), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('emotion', sa.String(length=40), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=False),
    sa.Column('audio_key', sa.String(length=400), nullable=False),
    sa.Column('timestamps_key', sa.String(length=400), nullable=True),
    sa.Column('est_cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_voiceovers_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['script_version_id'], ['script_versions.id'], name=op.f('fk_voiceovers_script_version_id_script_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voiceovers'))
    )
    op.create_index(op.f('ix_voiceovers_job_id'), 'voiceovers', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voiceovers_job_id'), table_name='voiceovers')
    op.drop_table('voiceovers')
    op.drop_index(op.f('ix_visual_assets_job_id'), table_name='visual_assets')
    op.drop_table('visual_assets')
    op.drop_index('ix_video_scenes_job_scene', table_name='video_scenes')
    op.drop_table('video_scenes')
    op.drop_table('video_projects')
    op.drop_table('script_versions')
    op.drop_table('youtube_uploads')
    op.drop_index(op.f('ix_thumbnails_job_id'), table_name='thumbnails')
    op.drop_table('thumbnails')
    op.drop_index('ix_system_logs_level_created', table_name='system_logs')
    op.drop_index('ix_system_logs_job_created', table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_scripts_job_id'), table_name='scripts')
    op.drop_table('scripts')
    op.drop_table('research')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_music_tracks_job_id'), table_name='music_tracks')
    op.drop_table('music_tracks')
    op.drop_index('ix_job_steps_job_stage', table_name='job_steps')
    op.drop_table('job_steps')
    op.drop_index('ix_api_usage_job', table_name='api_usage')
    op.drop_index('ix_api_usage_created', table_name='api_usage')
    op.drop_table('api_usage')
    op.drop_index('ix_jobs_status_created', table_name='jobs')
    op.drop_index(op.f('ix_jobs_public_id'), table_name='jobs')
    op.drop_index('ix_jobs_channel_status', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('youtube_credentials')
    op.drop_index(op.f('ix_topics_fingerprint'), table_name='topics')
    op.drop_index('ix_topics_channel_status', table_name='topics')
    op.drop_table('topics')
    op.drop_table('scheduler_runs')
    op.drop_table('channel_settings')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_channels_slug'), table_name='channels')
    op.drop_table('channels')
    # ### end Alembic commands ###
